### PR TITLE
Exit purge

### LINKED ISSUE #78: Make nancy not so exit heavy
* **What are you trying to do?**
As part of #68 @DarthHater was trying to do some testing and it the fact that Nancy exits like its going out of style made it overly difficult. 

For now the exits have been put back in place instead of using a panic which made testing easier to do. 

General go guidance is as follows, so this is where we should start to move the codebase. 
```
The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.
```

* **What feature or behavior is this required for?**
No real feature just more of a tech debt/cleanup/make it better type thing.

* **How could we solve this issue? (Not knowing is okay!)**
Stop exiting so much and panic instead but at the same time we still will want to preserve the exit codes and the user friendly messages after this change. No stack trace should be presented to the user. 

* **Anything else?**
¯\_(ツ)_/¯ 

cc @bhamail / @DarthHater

### PR DESCRIPTION
**Pull request by bhamail**
Minimize places where we call os.Exit(), in preparation for conversion to using Cobra #134 

I think this is ready for review.

I was a little concerned about the CI build failing in the logger_test.go. Seemed to be an unrelated change. Rerunning the CI build and it just passed. Boggle. We should keep an eye out in case this is a heisenbug. 

BTW, we may have a decision point regarding "--command, -flag" syntax in the near future.

Fixes #78

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by DarthHater** [comment]
I'm sure that you still are cranking, but when I run `./nancy iq` I get a SIGSEGV: (after usage).

```
$ ./nancy iq
Usage:
        go list -m all | nancy iq [options]

Options:
  -application string
        Specify application ID for request
  -max-retries int
        Specify maximum number of tries to poll Nexus IQ Server (default 300)
  -server-url string
        Specify Nexus IQ Server URL/port (default "http://localhost:8070")
  -stage string
        Specify stage for application (default "develop")
  -token string
        Specify Nexus IQ token/password for request (default "admin123")
  -user string
        Specify Nexus IQ username for request (default "admin")
  -v    Set log level to Info
  -vv
        Set log level to Debug
  -vvv
        Set log level to Trace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14fc90f]

goroutine 1 [running]:
github.com/sonatype-nexus-community/nancy/customerrors.ErrorExit.Error(0x0, 0x0, 0x0, 0x0, 0x2, 0xc000213710, 0xc0001a3a18)
        /go/src/github.com/sonatype-nexus-community/nancy/customerrors/error.go:30 +0x3f
github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc000110040, 0xc0002209a0, 0x10703d2, 0x2, 0x0, 0x1056779, 0xc0001a3d78)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/json_formatter.go:67 +0x1cd
github.com/sirupsen/logrus.(*Entry).write(0xc0002209a0)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:277 +0x7c
github.com/sirupsen/logrus.Entry.log(0xc00013e070, 0xc000213710, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:253 +0x1c2
github.com/sirupsen/logrus.(*Entry).Log(0xc000220930, 0x2, 0xc0001a3f58, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:289 +0xeb
github.com/sirupsen/logrus.(*Entry).Error(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:318
main.main()
        /go/src/github.com/sonatype-nexus-community/nancy/main.go:64 +0x20b
```

**Comment by zendern** [comment]
> I'm sure that you still are cranking, but when I run `./nancy iq` I get a SIGSEGV: (after usage).
> 
> ```
> $ ./nancy iq
> Usage:
>         go list -m all | nancy iq [options]
> 
> Options:
>   -application string
>         Specify application ID for request
>   -max-retries int
>         Specify maximum number of tries to poll Nexus IQ Server (default 300)
>   -server-url string
>         Specify Nexus IQ Server URL/port (default "http://localhost:8070")
>   -stage string
>         Specify stage for application (default "develop")
>   -token string
>         Specify Nexus IQ token/password for request (default "admin123")
>   -user string
>         Specify Nexus IQ username for request (default "admin")
>   -v    Set log level to Info
>   -vv
>         Set log level to Debug
>   -vvv
>         Set log level to Trace
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14fc90f]
> 
> goroutine 1 [running]:
> github.com/sonatype-nexus-community/nancy/customerrors.ErrorExit.Error(0x0, 0x0, 0x0, 0x0, 0x2, 0xc000213710, 0xc0001a3a18)
>         /go/src/github.com/sonatype-nexus-community/nancy/customerrors/error.go:30 +0x3f
> github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc000110040, 0xc0002209a0, 0x10703d2, 0x2, 0x0, 0x1056779, 0xc0001a3d78)
>         /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/json_formatter.go:67 +0x1cd
> github.com/sirupsen/logrus.(*Entry).write(0xc0002209a0)
>         /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:277 +0x7c
> github.com/sirupsen/logrus.Entry.log(0xc00013e070, 0xc000213710, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:253 +0x1c2
> github.com/sirupsen/logrus.(*Entry).Log(0xc000220930, 0x2, 0xc0001a3f58, 0x1, 0x1)
>         /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:289 +0xeb
> github.com/sirupsen/logrus.(*Entry).Error(...)
>         /go/pkg/mod/github.com/sirupsen/logrus@v1.5.0/entry.go:318
> main.main()
>         /go/src/github.com/sonatype-nexus-community/nancy/main.go:64 +0x20b
> ```

re: this `Hopefully Jeffry will NOT look at this over the weekend. 😄`
@bhamail I believe the answer is yeah not going to happen 😝

**Comment by bhamail** [comment]
> re: this `Hopefully Jeffry will NOT look at this over the weekend. 😄`
> @bhamail I believe the answer is yeah not going to happen 😝

The was a snowballs chance.... ;)

Fix issue with `nil` Err object causing seg fault: 24f46c0

File: customerrors/error.go [hunk 1]
```diff
@@ -18,33 +18,20 @@ package customerrors
...
+	ExitCode int
 }
 
-func Check(err error, message string) {
-	if err != nil {
-		location, _ := LogFileLocation()
-		myErr := SwError{Message: message, Err: err}
-		LogLady.WithField("error", err).Error(message)
-		fmt.Println(myErr.Error())
-		fmt.Printf("For more information, check the log file at %s\n", location)
```
Comment (DarthHater) [inline customerrors/error.go:46]: I'm not sure exactly where you may have moved this, but this was sorta important. Do you mind linking me to where it's been implemented since this PR is kinda big?

File: cyclonedx/cyclonedx_test.go [hunk 2]
```diff
@@ -24,11 +24,11 @@ import (
 	"github.com/package-url/packageurl-go"
 	"github.com/shopspring/decimal"
 	"github.com/sonatype-nexus-community/nancy/types"
-	assert "gopkg.in/go-playground/assert.v1"
+	"gopkg.in/go-playground/assert.v1"
 )
 
 func TestCreateSBOMFromPackageURLs(t *testing.T) {
-	results := []packageurl.PackageURL{}
+	var results []packageurl.PackageURL
```
Comment (DarthHater) [inline cyclonedx/cyclonedx_test.go:31]: Are these linter changes?

File: customerrors/error.go (hunk 1 above)
Comment (bhamail) [reply customerrors/error.go:46]: It's been replaced by returning `error` and using the customer `ExitError` where a specific exit code needed to bubble up the stack.

File: cyclonedx/cyclonedx_test.go (hunk 2 above)
Comment (bhamail) [reply cyclonedx/cyclonedx_test.go:31]: Yes, I was just going through linter suggestions. Happy to revert if desired.

File: main.go [hunk 3]
```diff
@@ -46,34 +47,65 @@ import (
...
-		LogLady.Info("Nancy parsing config for IQ")
-		config, err := configuration.ParseIQ(os.Args[2:])
-		if err != nil {
-			flag.Usage()
-			os.Exit(1)
-		}
-		LogLady.WithField("config", config).Info("Obtained IQ config")
-		processIQConfig(config)
-		LogLady.Info("Nancy finished parsing config for IQ")
+		err = doIq(os.Args[2:])
```
Comment (DarthHater) [inline main.go:52]: I like that you simplified the func name, but now it's a lil impossible to tell what it actually does. `doIq` is a bit too simple, I think. As well, it should likely be `doIQ`, as general golang convention is to capitalize stuff like that (`URL` vs `Url`, etc...)

File: cyclonedx/cyclonedx_test.go (hunk 2 above)
Comment (DarthHater) [reply cyclonedx/cyclonedx_test.go:31]: Naw no big deal, just kinda curious why it happened.

File: customerrors/error.go (hunk 1 above)
Comment (DarthHater) [reply customerrors/error.go:46]: Right, but where's the part that tells someone to look at their log file for more information?

File: audit/csvformatter.go [hunk 4]
```diff
@@ -57,33 +56,56 @@ func (f *CsvFormatter) Format(entry *Entry) ([]byte, error) {
...
+		var err error
+		if err = f.write(w, []string{"Summary"}); err != nil {
+			return nil, err
+		}
+		if err = f.write(w, summaryHeader); err != nil {
+			return nil, err
+		}
+		if err = f.write(w, summaryRow); err != nil {
+			return nil, err
+		}
```
Comment (DarthHater) [inline audit/csvformatter.go:68]: Holy code duplication batperson. I'm counting 11 or so blocks that are looking almost the same. Any way to simplify this down?

File: configuration/parse.go [hunk 5]
```diff
@@ -88,7 +88,8 @@ func ParseIQ(args []string) (config IqConfiguration, err error) {
 Options:
 `)
 		iqCommand.PrintDefaults()
-		os.Exit(2)
+		//os.Exit(2)
+		// Avoid exit calls, but caller should use exit code 2 when handling
```
Comment (DarthHater) [inline configuration/parse.go:92]: I would remove these comments

File: configuration/parse.go [hunk 6]
```diff
@@ -173,7 +174,8 @@ func Parse(args []string) (Configuration, error) {
 Options:
 `)
 		flag.PrintDefaults()
-		os.Exit(2)
+		// os.Exit(2)
+		// Avoid exit calls, but caller should use exit code 2 when handling
```
Comment (DarthHater) [inline configuration/parse.go:178]: I would remove these comments, too

File: customerrors/error.go [hunk 7]
```diff
@@ -18,33 +18,20 @@ package customerrors
...
-		fmt.Println("nancy version:", buildversion.BuildVersion)
-		myErr.Exit()
+func (ee ErrorExit) Error() string {
+	var errString string
+	if ee.Err != nil {
+		errString = ee.Err.Error()
+	} else {
+		errString = "nil"
```
Comment (DarthHater) [inline customerrors/error.go:34]: Why `"nil"`? There is no such thing as a nil string, why not `""`?

File: main_test.go [hunk 8]
```diff
@@ -33,3 +40,194 @@ func TestBadArgs(t *testing.T) {
...
+	purls := []string{"pkg:github/BurntSushi/toml@0.3.1"}
+	invalidPurls := []string{"invalidPurl"}
+	noColor := true
+	quiet := true
+	config := configuration.Configuration{Formatter: &audit.AuditLogTextFormatter{Quiet: &quiet, NoColor: &noColor}}
+	err := checkOSSIndex(purls, invalidPurls, config)
+	assert.NoError(t, err)
+}
+
+func TestDoOssi(t *testing.T) {
```
Comment (DarthHater) [inline main_test.go:225]: I am always SUPER wary of testing private methods. Do you think we really need to do this, versus an Integration test via dogfooding, etc... that tests more "public" expected behavior?

File: customerrors/error.go (hunk 1 above)
Comment (bhamail) [reply customerrors/error.go:46]: > Right, but where's the part that tells someone to look at their log file for more information?

Ah, I see your point now. I went back through all the places that used to call the old "check" method, and changed them to call a new "constructor" method the prints the old message about where to look in the logs for more info, and returns a new ErrorExit to bubble up the call stack.  
ccc94e1

File: main.go (hunk 3 above)
Comment (bhamail) [reply main.go:52]: These `do*` methods will likely map directly to new Cobra `command` structures. I will try to come up with better names for the Cobra commands. For now, the main goal was to simplify the main method enough so I could grok replacing the `os.Exit` stuff with centralized "exit processing" in `main()`.

File: audit/csvformatter.go (hunk 4 above)
Comment (bhamail) [reply audit/csvformatter.go:69]: Agreed. I'm open to suggestions here. Smells funny, but I'm not seeing a less stanky approach yet.

File: configuration/parse.go (hunk 5 above)
Comment (bhamail) [reply configuration/parse.go]: > I would remove these comments

Done ccc94e1

File: configuration/parse.go (hunk 6 above)
Comment (bhamail) [reply configuration/parse.go]: > I would remove these comments, too

Done ccc94e1

File: customerrors/error.go (hunk 7 above)
Comment (bhamail) [reply customerrors/error.go]: Good point. Changed to "".  ccc94e1

File: main_test.go (hunk 8 above)
Comment (bhamail) [reply main_test.go:230]: > I am always SUPER wary of testing private methods. Do you think we really need to do this, versus an Integration test via dogfooding, etc... that tests more "public" expected behavior?

I felt naked trying to change all the `os.Exit` calls with neither public IT's, nor unit tests of the code being changed. I therefore added some very specific unit tests to enable the refactoring at hand. I agree that IT's at a higher level would be nice to have, but I also believe this is a "chicken and the egg" problem - can't write the high level IT's with all those pesky `os.Exit` calls. Can't do true refactoring (where "refactoring" means making changes that can be proven not to break existing behavior) without unit tests or IT's.

So, I'd be happy to see unit tests be replaced by higher level IT's, which should hopefully be easier to do once the `os.Exit` beast is slain.

File: main.go [hunk 9]
```diff
@@ -181,18 +225,24 @@ func processIQConfig(config configuration.IqConfiguration) {
 	if config.Application == "" {
 		LogLady.Info("No application specified, printing usage and exiting clean")
```
Comment (bhamail) [inline main.go:226]: Should a missing "application" arg really exist "clean"? Feels like maybe it should be an error code return value? (Which I added below, but I just noticed the log comment above).

File: main_test.go (hunk 8 above)
Comment (DarthHater) [reply main_test.go:230]: I'll see if I can noodle out a proper IT framework. I agree it would be super useful.

File: main.go (hunk 9 above)
Comment (DarthHater) [reply main.go:226]: I think you are right, feel free to go with what makes sense!

Comment (bhamail) [reply main.go]: Done f369b29

File: audit/csvformatter.go (hunk 4 above)
Comment (DarthHater) [reply audit/csvformatter.go:69]: Maybe an anon function in the function like:

```
	writeAndCheckError = func(w *csv.Writer, value []string) {
		if err = f.write(w, value); err != nil {
			return nil, err
		}
	}
```

Haven't tested it myself but that MIGHT work. Just not sure if it will return in the function itself or return to the block where you call it.

**Comment by bhamail** [comment]
no objections, and some implicit approval, so merging this puppy in a bit.

**Comment by bhamail** [comment]
CAPS LOCK FRIDAY!
