### PR TITLE
Welp, let's let redirection work too

### LINKED ISSUE #92: Inconsistency when stdin is from file [bug]
### Steps to reproduce

1. Try variant 1:

        go list -m all | nancy

2. Try variant 2:

        go list -m all > go-list.txt
        nancy < go-list.txt

#### Actual result
The variant 1 works OK, variant 2 does not work (prints the usage):
~~~
C:\nancy>go list -m all | nancy
<...>
2020/03/11 22:45:54 Nancy version: development
Nancy version: development
[1/38][1mpkg:golang/github.com/AndreasBriese/bbloom@0.0.0-20180913140656-343706a395b7[0m[38;5;251m   No known vulnerabilities against package/version
[0m[2/38][1mpkg:golang/github.com/BurntSushi/toml@0.3.1[0m[38;5;251m   No known vulnerabilities against package/version
<...>
[0m[38/38][1mpkg:golang/github.com/go-yaml/yaml@2.2.2[0m[38;5;251m   No known vulnerabilities against package/version
[0m
Audited dependencies:38,Vulnerable:[1;31m0[0m

C:\nancy>go list -m all > go-list.txt

C:\nancy>nancy < go-list.txt
<...>
2020/03/11 22:46:14 Nancy version: development
Usage:
        go list -m all | nancy [options]
        go list -m all | nancy iq [options]
        nancy [options] </path/to/Gopkg.lock>
        nancy [options] </path/to/go.sum>

Options:
<...>
~~~

#### Expected result
Both variants work identically.

cc @bhamail / @DarthHater

### PR DESCRIPTION
**Pull request by DarthHater**
In #92 we discovered that Nancy would only accept piped stdin, not redirected. This PR aims to fix that!

This pull request makes the following changes:
* Adds a new `checkStdIn()` function to remove some duplicate code
* Maintains same behavior of previous StdIn check, but uses `os.ModeCharDevice` to check if something is in StdIn

It relates to the following issue #s:
* Fixes #92

cc @bhamail / @DarthHater / @zendern / @fitzoh / @AndreyMZ

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -174,68 +174,59 @@ func processIQConfig(config configuration.IqConfiguration) {
...
+	LogLady.Info("Auditing purls with OSS Index")
+	checkOSSIndex(purls, nil, config)
+}
+
+func checkStdIn() {
+	stat, _ := os.Stdin.Stat()
+	if (stat.Mode() & os.ModeCharDevice) == 0 {
+		LogLady.Info("StdIn is valid")
+	} else {
+		LogLady.Error("StdIn is invalid")
```
Comment (zendern) [inline main.go]: Is it worthwhile throwing out what Mode()/ os.ModeCharDevice it was?? `invalid` is good but more info might be better ..... also might be overkill.

Comment (DarthHater) [reply main.go]: Naw, I'm in to it!

Comment (DarthHater) [reply main.go]: Ok on checking this, it's basically empty when nothing is there. I'll add a better message as a result.

Comment (DarthHater) [reply main.go]: In: 72503e0

Comment (zendern) [reply main.go]: 👍  :shipit: real good
