### PR TITLE
Initial cleanup of error messages

### LINKED ISSUE #115: Cleanup error messaging
* **What are you trying to do?**
Cleanup the output of the cli..... steps to reproduce

1. Install nancy
2. Execute `nancy --version`
3. Notice the no such file or directory error...probably not important to show that error. 
```
nancy --version                                                                                           [4b539b9]
open /Users/zender/.ossindex/.oss-index-config: no such file or directory
0.1.17
build time: 2020-04-10T19:19:52Z
build commit: ddaa880e12e6ce183caa4ff5f55fda1d16b94390
```

* **What feature or behavior is this required for?**
Nothing really .... just cleaning stuff up. 

* **How could we solve this issue? (Not knowing is okay!)**
First thought is to change that to a logLady instead of the println that it probably is.

* **Anything else?**

cc @bhamail / @DarthHater

### PR DESCRIPTION
**Pull request by designergod420**
Working with @DarthHater we went through Nancy and looked for any instances where we were using fmt to print an error and either replaced with a customerror.check or logged with LogLady. 

It relates to the following issue #s:
* Fixes #115 

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by DarthHater** [comment]
@zendern @bhamail so this linter failure has me going 🤷 ? Do either of you know what it means?

**Comment by bhamail** [comment]
Maybe unrelated to linter error, but I get the following when trying to build locally:

```
$ go test ./...
import cycle not allowed
package github.com/sonatype-nexus-community/nancy
        imports github.com/sonatype-nexus-community/nancy/audit
        imports github.com/sonatype-nexus-community/nancy/customerrors
        imports github.com/sonatype-nexus-community/nancy/logger
        imports github.com/sonatype-nexus-community/nancy/customerrors
can't load package: import cycle not allowed
package github.com/sonatype-nexus-community/nancy
        imports github.com/sonatype-nexus-community/nancy/audit
        imports github.com/sonatype-nexus-community/nancy/customerrors
        imports github.com/sonatype-nexus-community/nancy/logger
        imports github.com/sonatype-nexus-community/nancy/customerrors
```

**Comment by DarthHater** [comment]
@bhamail you'll laugh, but we got that locally too. I thought it was from forking the repo. I'll take a dive with @designergod420 in a bit!

**Comment by bhamail** [comment]
> @bhamail you'll laugh, but we got that locally too. I thought it was from forking the repo. I'll take a dive with @designergod420 in a bit!

Maybe a useful clue:
nancy/customerrors/error.go -> imports: . "github.com/sonatype-nexus-community/nancy/logger"

nancy/logger/logger.go -> imports: "github.com/sonatype-nexus-community/nancy/customerrors"

**Comment by DarthHater** [comment]
Yeah, it was the `logger`. Fixed it up and sent a PR to @designergod420 at here: https://github.com/designergod420/nancy/pull/1

**Comment by DarthHater** [comment]
@bhamail @zendern @fitzoh this should be good for review if you wanna bless it!

File: configuration/parse.go [hunk 1]
```diff
@@ -174,7 +173,6 @@ Options:
 
 	err := loadConfigFromFile(ConfigLocation, &config)
 	if err != nil {
-		fmt.Println(err)
```
Comment (fitzoh) [inline configuration/parse.go:177]: should probably log the error here and above, big difference between a missing file and a malformed file

Comment (fitzoh) [reply configuration/parse.go:177]: or add logging to the error site

File: logger/old_logger.go [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+func GetLogFileLocation() (result string) {
+	result, _ = os.UserHomeDir()
+	err := os.MkdirAll(path.Join(result, types.OssIndexDirName), os.ModePerm)
+	if err != nil {
+		fmt.Println(err)
+		return ""
+	}
+	result = path.Join(result, types.OssIndexDirName, DefaultLogFile)
+	return
+}
```
Comment (fitzoh) [inline logger/old_logger.go:21]: I feel like `old_logger` might be worthy of a comment

File: configuration/parse.go (hunk 1 above)
Comment (designergod420) [reply configuration/parse.go:177]: In : ba07c9d

Comment (fitzoh) [reply configuration/parse.go:177]: Same thing for `loadIQConfigFromFile`

File: logger/old_logger.go (hunk 2 above)
Comment (designergod420) [reply logger/old_logger.go:38]: In: 23e760d

File: configuration/parse.go (hunk 1 above)
Comment (designergod420) [reply configuration/parse.go:177]: In: 23492bf

Comment (fitzoh) [reply configuration/parse.go:177]: Actually 1 more nit to pick... `Unable to read file` might be a little confusing without context, might want to mention `Unable to read (IQ|Ossindex) config file` (possibly with the path as a logged field?)
